name: hackathon
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - openai
    - selenium
    - transformers
    - torch
    - pillow
    - streamlit-mic-recorder
    - webdriver-manager
    - toml
